### ISSUE TITLE
Opening adventurer plate breaks profile until the window is closed.

### ISSUE THREAD

**Issue by RisaDev** [Aether-Tools/CustomizePlus#18]
An issue with Penumbra.GameData or Penumbra.String?

Log:

```
02:12:42.845 | ERR | [CustomizePlus] Exception while rendering armatures:
		System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
	   at Penumbra.String.Functions.ByteStringFunctions.ComputeCrc32AsciiLowerAndSize(Byte* ptr, Int32& crc32Ret, Boolean& isLower, Boolean& isAscii) in D:\a\CustomizePlus\CustomizePlus\submodules\Penumbra.String\Functions\Crc.cs:line 98
	   at Penumbra.String.ByteString..ctor(Byte* path) in D:\a\CustomizePlus\CustomizePlus\submodules\Penumbra.String\ByteString.Construction.cs:line 45
	   at Penumbra.GameData.Actors.ActorResolver.GetCardPlayer(ActorIdentifierFactory factory) in D:\a\CustomizePlus\CustomizePlus\submodules\Penumbra.GameData\Actors\ActorResolver.cs:line 130
	   at CustomizePlus.Game.Services.GameObjectService.GetTrueActorForSpecialTypeActor(ActorIdentifier identifier) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Game\Services\GameObjectService.cs:line 136
	   at CustomizePlus.Profiles.ProfileManager.GetEnabledProfilesByActor(ActorIdentifier actorIdentifier)+MoveNext() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Profiles\ProfileManager.cs:line 496
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
	   at CustomizePlus.Armatures.Services.ArmatureManager.RefreshArmatures() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 143
	   at CustomizePlus.Armatures.Services.ArmatureManager.OnRender() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 81
```

**Comment by RisaDev** [comment]
Seems like this was fixed by one of Dalamud updates? Awaits additional confirmation.

**Comment by RisaDev** [comment]
Will be fixed in the next release
