### ISSUE TITLE
Entering GPose creates new armature which cannot be cleaned up and possibly leads to other issues

### ISSUE THREAD

**Issue by RisaDev** [Aether-Tools/CustomizePlus#39]
Opening GPose with active armature sometimes results in new armature being created on identifier `%CharacterName% (Any World)` which bugs out when GPose is closed. 
```
ERR | [CustomizePlus] Exception while rendering armatures:
		System.Collections.Generic.KeyNotFoundException: The given key '##### (Any World)' was not present in the dictionary.
	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	   at CustomizePlus.GameData.Services.ObjectManager.get_Item(ActorIdentifier key) in F:\Sources\FFXIV\Aether-Tools\CustomizePlus\CustomizePlus.GameData\Services\ObjectManager.cs:line 194
	   at CustomizePlus.Armatures.Services.ArmatureManager.ApplyArmatureTransforms() in F:\Sources\FFXIV\Aether-Tools\CustomizePlus\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 199
	   at CustomizePlus.Armatures.Services.ArmatureManager.OnRender() in F:\Sources\FFXIV\Aether-Tools\CustomizePlus\CustomizePlus\Armatures\Services\ArmatureManager.cs:line 82
```

![image](https://github.com/user-attachments/assets/dceb36ea-2e45-44ec-b572-d3985b509e02)

It is possible this also results in #40

**Comment by RisaDev** [comment]
This armature now cleans up properly as of latest version
