### ISSUE TITLE
Issue loading customize plus while testing new version for 7.1

### ISSUE THREAD

**Issue by Dalrend** [Aether-Tools/CustomizePlus#48]
Hello, was testing out customize plus and received this error, and this stack trace to follow said error:

16:20:33.750 | ERR | [CustomizePlus] Error instantiating plugin: System.TypeLoadException: Could not load type 'Lumina.Excel.ExcelRow' from assembly 'Lumina, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
	   at ECommons.ECommonsMain.Init(IDalamudPluginInterface pluginInterface, IDalamudPlugin instance, Module[] modules)
	   at CustomizePlus.Plugin..ctor(IDalamudPluginInterface pluginInterface) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Plugin.cs:line 25

16:20:33.750 | ERR | [LOCALPLUGIN] Error while loading "CustomizePlus", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create CustomizePlus.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.TypeLoadException: Could not load type 'Lumina.Excel.ExcelRow' from assembly 'Lumina, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
	   at ECommons.ECommonsMain.Dispose()
	   at CustomizePlus.Plugin..ctor(IDalamudPluginInterface pluginInterface) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Plugin.cs:line 42
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 583
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 581
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 396

wanted to pass this along if it is not relevant let me know and ill get this issue closed!

here's a screenshot of the picture:
![image](https://github.com/user-attachments/assets/b4289989-1e09-459e-854a-836896185c1d)

all I did to encounter this bug was attempted to try the testing version and the customize+ interface wouldn't show up

**Comment by StoiaCode** [comment]
Dalamud is in Testing and C+ isnt released, what your own build does is none of our concern. 
Be happy I respond instead of Risa.
